language: perl
sudo: false
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

cache:
  directories:
    - cache

matrix:
  fast_finish: true

script:
  - if [ "$TRAVIS_PERL_VERSION" "5.22" ]; then make pack; fi
  - make test

# https://docs.travis-ci.com/user/deployment/releases
deploy:
  provider: releases
  api_key:
    secure: lE3YmAY2AR4QJE+62fFljzG9TruoNgEcg/+MxokLsufgN3ZDTKXVbyFaJySIfFRJ3VezRvh84JLzrcOeQZxN14Qruqnp1ZJ5NoMDT9HUxBJmikBTfopJobUFeQPvZXBb2o+XrF57KNtRhFGLoeXMvMVoPO9IlQ1zv4Z6dtJe2GM=
  file:
    - check_raid.pl
  skip_cleanup: true
  on:
    repo: glensc/nagios-plugin-check_raid
    # deploy from 5.22 version, the other versions somewhy bundle too much dependencies
    perl: '5.22'
    tags: true

# vim:ft=yaml:et:ts=2:sw=2
