language: perl
sudo: false
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

cache:
  directories:
    - cache

before_script:
  - cpanm -n App::FatPacker
  - cpanm -n App::FatPacker::Simple

script:
  - make pack

# vim:ft=yaml:et:ts=2:sw=2
